blueprint:
  name: deCONZ - IKEA five button remote
  description: Tradfri 5 Button Remote Bluetprint
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: deconz
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control
    button_middle_short:
      name: Middle button - short press
      description: Action to run on short middle button press
      default: []
      selector:
        action: {}
    button_top_short:
      name: Top button - short press
      description: Action to run on short top button press
      default: []
      selector:
        action: {}
    button_top_long:
      name: Top button - long press
      description: Action to run on long top button press
      default: []
      selector:
        action: {}
    button_bottom_short:
      name: Buttom button - short press
      description: Action to run on short bottom button press
      default: []
      selector:
        action: {}
    button_bottom_long:
      name: Bottom button - long press
      description: Action to run on long bottm button press
      default: []
      selector:
        action: {}
    button_left_short:
      name: Left button - short press
      description: Action to run on short left button press
      default: []
      selector:
        action: {}
    button_left_long:
      name: Left button - long press
      description: Action to run on long left button press
      default: []
      selector:
        action: {}
    button_right_short:
      name: Right button - short press
      description: Action to run on short right button press
      default: []
      selector:
        action: {}
    button_right_long:
      name: Right button - long press
      description: Action to run on long right button press
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/deconz-ikea-five-button-remote-for-lights/255403
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'remote'
action:
- variables:
    event: '{{ trigger.event.data.event }}'
- choose:
  - conditions:
    - '{{ event == 1002 }}'
    sequence: !input 'button_middle_short'
  - conditions:
    - '{{ event == 2002 }}'
    sequence: !input 'button_top_short'
  - conditions:
    - '{{ event == 2001 }}'
    sequence: !input 'button_top_long'
  - conditions:
    - '{{ event == 3002 }}'
    sequence: !input 'button_bottom_short'
  - conditions:
    - '{{ event == 3001 }}'
    sequence: !input 'button_bottom_long'
  - conditions:
    - '{{ event == 4002 }}'
    sequence: !input 'button_left_short'
  - conditions:
    - '{{ event == 4001 }}'
    sequence: !input 'button_left_long'
  - conditions:
    - '{{ event == 5002 }}'
    sequence: !input 'button_right_short'
  - conditions:
    - '{{ event == 5001 }}'
    sequence: !input 'button_right_long'
